### ISSUE TITLE
chore: refactor init scripts

### ISSUE THREAD

**Issue by stevennovaryo** [stevennovaryo/cp-contest-template#1]
### Tasks

Add a pre-commit script that can:
  - [ ] Install Python for those who don't have it, and differentiate between Windows dan Ubuntu.
  - [ ] Find how to install dependencies in Windows.
  - [ ] Find how to check if dependencies are already installed. (probably use aliases)

**Comment by VioAlbert** [comment]
As discussed, the issue will be addressed by refactoring `init.sh` and `init.bat` rather than making the pre-commit itself, since installing dependencies during pre-commit is not a good practice. The issue will be renamed as such.
