### ISSUE TITLE
chore: move files from troc-32 to this repo

### ISSUE THREAD

**Issue by stevennovaryo** [stevennovaryo/cp-contest-template#5]
## Description

Because the project was initiated in TROC 32 repository, the files need to be moved to this repository.

### Tasks
- [ ] Move files from TROC 32.
- [ ] Check the gitignore, if there is something else we need to add.
- [ ] Check we need to do further action to files in `contoh` or not,
